1.1 Creating Matrices

In [67]:
import numpy as np

In [68]:
# Creating a 2x2 array
arr = [[1, 2], [3, 4]]
print(arr)

[[1, 2], [3, 4]]


In [69]:
# Convert to NumPy
np.array(arr)

array([[1, 2],
       [3, 4]])

In [70]:
import torch

In [71]:
# Convert to PyTorch Tensor
torch.Tensor(arr)

tensor([[1., 2.],
        [3., 4.]])

1.2 Create Matrices with Default Values

In [72]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [73]:
torch.ones((2,2))

tensor([[1., 1.],
        [1., 1.]])

In [74]:
np.random.rand(2,2)

array([[0.56804456, 0.92559664],
       [0.07103606, 0.0871293 ]])

In [75]:
torch.rand(2,2)

tensor([[0.0223, 0.1689],
        [0.2939, 0.5185]])

1.3 Seeds for Reproducibility

In [76]:
# Seed 
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [77]:
# Seed
np.random.seed(0)
np.random.rand(2,2)

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [78]:
# No seed
np.random.rand(2,2)

array([[0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ]])

In [79]:
# No seed
np.random.rand(2, 2)

array([[0.96366276, 0.38344152],
       [0.79172504, 0.52889492]])

In [80]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [81]:
# Torch Seed
torch.manual_seed(0)
torch.rand(2,2)

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [82]:
# Torch No Seed
torch.rand(2,2)

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [83]:
# Torch No Seed
torch.rand(2,2)

tensor([[0.4556, 0.6323],
        [0.3489, 0.4017]])

Seed for GPU is different for now...

In [84]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

1.3 NumPy and Torch Bridge

NumPy to Torch

In [85]:
# Numpy array
np_array = np.ones((2,2))

In [86]:
print(np_array)

[[1. 1.]
 [1. 1.]]


In [87]:
print(type(np_array))

<class 'numpy.ndarray'>


In [88]:
# Convert to Torch Tensor
torch_tensor = torch.from_numpy(np_array)

In [89]:
print(torch_tensor)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)


In [90]:
print(type(torch_tensor))

<class 'torch.Tensor'>


In [91]:
np_array_new = np.ones((2,2), dtype=np.int8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int8)

The conversion supports:
1. double
2. float
3. int64, int32, int8, uint8

In [92]:
# Data types matter
np_array_new = np.ones((2,2), dtype=np.int64)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]])

In [93]:
# Data types matter
np_array_new = np.ones((2,2), dtype=np.int32)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [94]:
# Data types matter
np_array_new = np.ones((2,2), dtype=np.uint8)
torch.from_numpy(np_array_new)

tensor([[1, 1],
        [1, 1]], dtype=torch.uint8)

In [95]:
# Data types matter
np_array_new = np.ones((2,2), dtype=np.float64)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [96]:
# Data types matter
np_array_new = np.ones((2,2), dtype=np.float32)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]])

In [97]:
# Data types matter
np_array_new = np.ones((2,2), dtype=np.double)
torch.from_numpy(np_array_new)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

Torch to NumPy

In [98]:
torch_tensor = torch.ones(2,2)

In [99]:
type(torch_tensor)

torch.Tensor

In [100]:
torch_to_numpy = torch_tensor.numpy()

In [101]:
type(torch_to_numpy)

numpy.ndarray

1.4 Tensors on CPU vs GPU

In [102]:
# CPU
tensor_cpu = torch.ones(2,2)

In [103]:
# CPU to GPU
if torch.cuda.is_available():
    tensor_cpu.cuda()

In [104]:
# GPU to CPU
tensor_cpu.cpu()

tensor([[1., 1.],
        [1., 1.]])

1.5 Tensor Operations

Resizing Tensor

In [105]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [106]:
print(a.size())

torch.Size([2, 2])


In [107]:
a.view(4)

tensor([1., 1., 1., 1.])

In [108]:
a.view(4).size()

torch.Size([4])

Element-wise Addition

In [109]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [110]:
b = torch.ones(2,2)
print(b)

tensor([[1., 1.],
        [1., 1.]])


In [111]:
# Element-wise addition
c = a + b 
print(c) 

tensor([[2., 2.],
        [2., 2.]])


In [112]:
# Element-wise addition
c = torch.add(a,b)
print(c)

tensor([[2., 2.],
        [2., 2.]])


In [113]:
# In-place addition
print('Old c tensor')
print(c)

c.add_(a)

print('-'*60)

print('New c tensor')
print(c)

Old c tensor
tensor([[2., 2.],
        [2., 2.]])
------------------------------------------------------------
New c tensor
tensor([[3., 3.],
        [3., 3.]])


In [114]:
print(a)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


In [115]:
a - b   

tensor([[0., 0.],
        [0., 0.]])

In [116]:
# Not in-place
print(a.sub(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [117]:
# Inplace
print(a.sub_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


Element-Wise Multiplication

In [118]:
a = torch.ones(2,2)
print(a)
b = torch.zeros(2,2)
print(b)

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [119]:
a * b

tensor([[0., 0.],
        [0., 0.]])

In [120]:
# Not in-place
print(torch.mul(a,b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [121]:
# In-place
print(a.mul_(b))
print(a)

tensor([[0., 0.],
        [0., 0.]])
tensor([[0., 0.],
        [0., 0.]])


Element-Wise Division

In [122]:
a = torch.ones(2,2)
b = torch.zeros(2,2)

In [123]:
b / a

tensor([[0., 0.],
        [0., 0.]])

In [124]:
torch.div(b,a)

tensor([[0., 0.],
        [0., 0.]])

In [125]:
# Inplace
b.div_(a)

tensor([[0., 0.],
        [0., 0.]])

Tensor Mean

1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10 = 55

mean = 55/10 = 5.5

In [126]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.size()

torch.Size([10])

In [127]:
a.mean(dim=0)

tensor(5.5000)

In [128]:
a.mean(dim=1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [129]:
a = torch.Tensor([[1, 2 ,3, 4, 5, 6, 7, 8, 9, 10], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])

In [130]:
a.size()

torch.Size([2, 10])

In [131]:
a.mean(dim=1)

tensor([5.5000, 5.5000])

Tensor Standard Deviation

In [132]:
a = torch.Tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a.std(dim=0)

tensor(3.0277)

Summary:

1. Create Matrices

2. Create Matrices with Default Initialization Values

    - Zeros

    - Ones

3. Initialize Seeds for Reproducibility on GPU and CPU

4. Convert Matrices: NumPy => Torch and Torch => NumPy

5. Move Tensors: CPU => GPU and GPU => CPU

6. Run Important tensor Operations

    - Elements-wise addition, subtraction, multiplication and division

    - Resize

    - Calculate mean
    
    - Calculate standard deviation